<?php
//
// iTop module definition file
//

SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'combodo-mfa-base/1.0.1',
	[
		// Identification
		//
		'label' => 'Multi-factor authentication base',
		'category' => 'authentication',

		// Setup
		//
		'dependencies' => [
			'combodo-my-account/1.0.0',
			'itop-portal-base/3.2.0',
			'itop-attribute-class-set/1.0.0',
		],
		'mandatory' => true,
		'visible' => true,

		// Components
		//
		'datamodel' => [
			'vendor/autoload.php',
			'model.combodo-mfa-base.php', // Contains the PHP code generated by the "compilation" of datamodel.combodo-mfa-base.xml
			'src/Hook/MFABaseLoginExtension.php',
			'src/Hook/MFABaseMenu.php',
		],
		'webservice' => [

		],
		'data.struct' => [
			// add your 'structure' definition XML files here,
		],
		'data.sample' => [
			// add your sample data XML files here,
		],

		// Documentation
		//
		'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
		'doc.more_information' => '', // hyperlink to more information, if any

		// Default settings
		//
		'settings' => [
			'enabled' => true,
			'allowed-login-types' => ['form', 'basic', 'url', 'external'],
		],
	]
);
